language: csharp
mono: none
dotnet: 1.0.1
dist: trusty
sudo: required

script:
  - cd src/
  - dotnet restore && npm install
  - dotnet --verbose build -c Release
  - gulp compile
  - gulp clean:prod
  - ls ./wwwroot/js
  - dotnet bundle
